/**
 * Pipeable {@link Store.contract} shell — delegates to {@link contractDef}.
 *
 * @module internal/store/contract
 * @internal
 */

export {
  compileStoreContract,
  contractSpec,
  CUSTOM_APPEND_ALIAS,
  emptyPayloadSchema,
  isStoreContractValue,
  isStoreShapeDef,
  isStoreShapeInput,
  isStoreShapeLeaf,
  isStoreShapeMap,
  isStoreShapeTree,
  makeShapeRefs,
  makeStoreContractValue,
  makeStoreShape,
  mergeStoreContracts,
  materializeContractHandle,
  nestHandle,
  resolveShapeRef,
  shapeRowsByKey,
  toStoreContract,
  type AllShapeRows,
  type CustomMethodEntry,
  type ExtendCustom,
  type MergedCustom,
  type MethodsReturn,
  type NoCustom,
  type NormalizedShape,
  type NormalizedShapes,
  type NormalizeShape,
  type SchemaDecoded,
  type ShapeAppendFn,
  type ShapeHandle,
  type ShapeHandles,
  type ShapeReadFn,
  type ShapeRef,
  type ShapeRefs,
  type ShapesOfStore,
  type StoreClassWithShapes,
  type StoreContractDef,
  type StoreContractValue,
  type StoreMethodsFn,
  type StoreShapeDef,
  type StoreShapeInput,
  type StoreShapeInputLeaf,
  type StoreShapes,
  type StoreShapeTree,
} from "./contractDef";
