/**
 * Codegen: walk a pages dir → typed `paths.gen.ts`.
 *
 * TypeScript cannot glob the filesystem at typecheck time. A small emit step
 * (or Vite plugin writing the same file) is what makes `FilePath` a real union.
 *
 * File templates use `[param]` (Waku-style on disk); Hyperlink Route paths use
 * `:param` — both are emitted.
 *
 * Run: `node examples/ui/file-router/scripts/gen-paths.mjs`
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const pagesDir = path.join(root, "fixtures/pages");
const outFile = path.join(root, "paths.gen.ts");

const EXT = /\.(tsx|ts|jsx|js)$/;

/** @param {string} abs */
const walk = (abs) => {
  /** @type {string[]} */
  const files = [];
  for (const ent of fs.readdirSync(abs, { withFileTypes: true })) {
    if (ent.name.startsWith("_")) continue; // layouts / root chrome — not destinations
    const next = path.join(abs, ent.name);
    if (ent.isDirectory()) files.push(...walk(next));
    else if (EXT.test(ent.name)) files.push(next);
  }
  return files;
};

/** file abs → file URL path (`[chapter].tsx` → `/docs/[chapter]`) */
const toFilePath = (abs) => {
  const rel = path.relative(pagesDir, abs).replace(/\\/g, "/");
  const noExt = rel.replace(EXT, "");
  const segs = noExt.split("/").filter((s) => s.length > 0);
  if (segs[segs.length - 1] === "index") segs.pop();
  return "/" + segs.join("/");
};

/** `/docs/[chapter]` → `/docs/:chapter` (Hyperlink Route template) */
const toRoutePath = (filePath) =>
  filePath.replace(/\[(\w+)\?\]/g, ":$1?").replace(/\[(\w+)\]/g, ":$1");

/** `/docs/[chapter]` → `docs_chapter` */
const toId = (filePath) => {
  if (filePath === "/") return "index";
  return filePath
    .slice(1)
    .replace(/\[(\w+)\??\]/g, "$1")
    .replace(/\//g, "_");
};

const entries = [...new Set(walk(pagesDir).map(toFilePath))]
  .sort((a, b) => a.localeCompare(b))
  .map((filePath) => ({
    id: toId(filePath),
    filePath,
    routePath: toRoutePath(filePath),
  }));

const filePathUnion = entries.map((e) => JSON.stringify(e.filePath)).join(" | ");
const routePathUnion = entries.map((e) => JSON.stringify(e.routePath)).join(" | ");
const idUnion = entries.map((e) => JSON.stringify(e.id)).join(" | ");

const body = `/**
 * GENERATED by \`scripts/gen-paths.mjs\` — do not edit.
 *
 * Typed union proof for the file-router prototype.
 */
export const fileEntries = ${JSON.stringify(entries, null, 2)} as const;

export const filePaths = [
${entries.map((e) => `  ${JSON.stringify(e.filePath)},`).join("\n")}
] as const;

export const routePaths = [
${entries.map((e) => `  ${JSON.stringify(e.routePath)},`).join("\n")}
] as const;

/** Disk / file-URL templates (\`[param]\`). */
export type FilePath = ${filePathUnion};

/** Hyperlink {@link Route} templates (\`:param\`). */
export type RoutePath = ${routePathUnion};

/** Stable route ids derived from those paths. */
export type FileRouteId = ${idUnion};

export type FileEntry = (typeof fileEntries)[number];
`;

fs.writeFileSync(outFile, body);
console.log(`wrote ${path.relative(process.cwd(), outFile)} (${entries.length} paths)`);
for (const e of entries) {
  console.log(`  ${e.id.padEnd(16)} file=${e.filePath}  route=${e.routePath}`);
}
