/**
 * GENERATED by last-ts file router — do not edit.
 */
export const fileEntries = [
  {
    "id": "index",
    "filePath": "/",
    "routePath": "/"
  },
  {
    "id": "about",
    "filePath": "/about",
    "routePath": "/about"
  },
  {
    "id": "docs_path",
    "filePath": "/docs/[...path]",
    "routePath": "/docs/*path"
  },
  {
    "id": "guides_slug",
    "filePath": "/guides/[slug]",
    "routePath": "/guides/:slug"
  },
  {
    "id": "view",
    "filePath": "/view",
    "routePath": "/view"
  }
] as const;

export const filePaths = [
  "/",
  "/about",
  "/docs/[...path]",
  "/guides/[slug]",
  "/view",
] as const;

export const routePaths = [
  "/",
  "/about",
  "/docs/*path",
  "/guides/:slug",
  "/view",
] as const;

export type FilePath = "/" | "/about" | "/docs/[...path]" | "/guides/[slug]" | "/view";
export type RoutePath = "/" | "/about" | "/docs/*path" | "/guides/:slug" | "/view";
export type FileRouteId = "index" | "about" | "docs_path" | "guides_slug" | "view";
export type FileEntry = (typeof fileEntries)[number];
