/**
 * GENERATED by hyperlink-ts file router — do not edit.
 */
export const fileEntries = [
  {
    "id": "index",
    "filePath": "/",
    "routePath": "/"
  },
  {
    "id": "api_pkg",
    "filePath": "/api/[pkg]",
    "routePath": "/api/:pkg"
  },
  {
    "id": "docs_chapter",
    "filePath": "/docs/[chapter]",
    "routePath": "/docs/:chapter"
  },
  {
    "id": "search",
    "filePath": "/search",
    "routePath": "/search"
  }
] as const;

export const filePaths = [
  "/",
  "/api/[pkg]",
  "/docs/[chapter]",
  "/search",
] as const;

export const routePaths = [
  "/",
  "/api/:pkg",
  "/docs/:chapter",
  "/search",
] as const;

export type FilePath = "/" | "/api/[pkg]" | "/docs/[chapter]" | "/search";
export type RoutePath = "/" | "/api/:pkg" | "/docs/:chapter" | "/search";
export type FileRouteId = "index" | "api_pkg" | "docs_chapter" | "search";
export type FileEntry = (typeof fileEntries)[number];
