/**
 * `hyp theme-keys emit` — write the VS Code colour key registry that the theme
 * editor offers when someone adds a key a theme has not set.
 *
 * VS Code publishes no machine-readable list of its colour keys, so the
 * registry is derived from the themes bundled with `shiki`, the same library
 * the app renders code with. Sixty-five real themes between them set far more
 * keys than any one of them does, which is enough to make the editor's Add list
 * real keys rather than guesses.
 *
 * What that leaves out: a key VS Code defines that none of the bundled themes
 * happens to set. What it lets in: a key that was renamed or deprecated after a
 * bundled theme was written. Both are visible in the output, because the
 * generated module records how many themes set each key.
 */
import { Data, Effect, Layer } from "effect";
import { Command, Flag } from "effect/unstable/cli";
import * as FileSystem from "effect/FileSystem";
import * as Path from "effect/Path";
import { NodeFileSystem, NodePath } from "@effect/platform-node";
import { pathToFileURL } from "node:url";

const nodeLayer: Layer.Layer<FileSystem.FileSystem | Path.Path> = Layer.mergeAll(
  NodeFileSystem.layer,
  NodePath.layer,
);

/** A bundled theme module that would not load. */
export class ThemeModuleError extends Data.TaggedError("ThemeModuleError")<{
  readonly path: string;
  readonly cause: unknown;
}> {}

/** No theme modules where the generator was told to look. */
export class ThemesMissingError extends Data.TaggedError("ThemesMissingError")<{
  readonly dir: string;
}> {}

/**
 * Dynamic `import()` of a file on disk. Effect has no module-loading service,
 * so the one Node API this needs is isolated here.
 */
const importModule = (absolute: string): Effect.Effect<unknown, ThemeModuleError> =>
  Effect.tryPromise({
    try: () => import(pathToFileURL(absolute).href) as Promise<unknown>,
    catch: (cause) => new ThemeModuleError({ path: absolute, cause }),
  });

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null;

/** The colour keys one bundled theme sets, or nothing if the module is not a theme. */
const colorKeysOf = (module: unknown): ReadonlyArray<string> => {
  if (!isRecord(module)) return [];
  const theme = isRecord(module.default) ? module.default : module;
  return isRecord(theme.colors) ? Object.keys(theme.colors) : [];
};

const themesDirFlag = Flag.string("themes").pipe(
  Flag.withDescription("Directory of bundled shiki theme modules."),
  Flag.withDefault("packages/agent-console-native/node_modules/shiki/dist/themes"),
);

const outFlag = Flag.string("out").pipe(
  Flag.withDescription("Generated registry module."),
  Flag.withDefault("packages/agent-console-native/src/vscodeColorKeys.gen.ts"),
);

const formatModule = (
  counts: ReadonlyMap<string, number>,
  themeCount: number,
): string => {
  // Most-set key first. The editor offers the head of each group when adding a
  // key, so the order decides which of a group's hundred keys someone is shown
  // before they have to search.
  const keys = [...counts.entries()]
    .sort(([keyA, countA], [keyB, countB]) => countB - countA || keyA.localeCompare(keyB))
    .map(([key]) => key);
  const rows = keys.map((key) => `  "${key}",`).join("\n");
  return `/**
 * Every workbench colour key the themes bundled with \`shiki\` set between them.
 *
 * Generated by \`pnpm hyp theme-keys emit\`. Do not edit by hand.
 *
 * ${String(keys.length)} keys, from ${String(themeCount)} themes. The theme editor reads this to offer
 * keys a theme has not set yet, which is the only way a key nobody has touched
 * is reachable at all.
 */

/**
 * Ordered by how many of the bundled themes set the key, most first, ties
 * broken by name. A group can run to hundreds of keys, so the order is what
 * decides which ones someone sees before reaching for search.
 */
export const VSCODE_COLOR_KEYS: ReadonlyArray<string> = [
${rows}
];
`;
};

const emit = Command.make("emit", { themes: themesDirFlag, out: outFlag }).pipe(
  Command.withDescription("Write the VS Code colour key registry from bundled shiki themes."),
  Command.withHandler(({ themes, out }) =>
    Effect.gen(function* () {
      const fs = yield* FileSystem.FileSystem;
      const path = yield* Path.Path;
      const dir = path.resolve(themes);
      const entries = yield* fs.readDirectory(dir);
      const modules = entries.filter((entry) => entry.endsWith(".mjs")).sort();
      if (modules.length === 0) {
        return yield* new ThemesMissingError({ dir });
      }
      const counts = new Map<string, number>();
      let themeCount = 0;
      for (const file of modules) {
        const keys = colorKeysOf(yield* importModule(path.join(dir, file)));
        if (keys.length === 0) continue;
        themeCount += 1;
        for (const key of keys) counts.set(key, (counts.get(key) ?? 0) + 1);
      }
      const outFile = path.resolve(out);
      yield* fs.writeFileString(outFile, formatModule(counts, themeCount));
      yield* Effect.logInfo(`theme-keys: wrote ${outFile} (${String(counts.size)} keys from ${String(themeCount)} themes)`);
    }).pipe(Effect.provide(nodeLayer)),
  ),
);

export const themeKeys = Command.make("theme-keys").pipe(
  Command.withDescription("VS Code colour key registry for the theme editor."),
  Command.withSubcommands([emit]),
);
